### PR TITLE
add writeup for may

### PR DESCRIPTION
**Pull request by lpmi-13**

### CODE REVIEW

**Comment by lpmi-13** [comment]
@benfoxall this still needs one of the screenshots you took from the intro, as well as any other details you feel like adding.

**Comment by benfoxall** [comment]
@lpmi-13 will do! I'm a bit stacked today, but will try and add tonight.  Great write up so far!

**Comment by omgmog** [comment]
image

**Review by spikeheap — APPROVED** [review]

**Comment by omgmog** [comment]
🎉

**Pull request merged**
