### PR TITLE
Remove "GMT", because ⛱

### PR DESCRIPTION
**Pull request by benfoxall**
@lpmi-13 pointed out that the start time isn't correct!

image

Should we just drop off the gmt?  Or is there a neater way to show the timezone too?

### CODE REVIEW

**Comment by benfoxall** [comment]
(discussed a bit more on slack.). We totally need a timezone, so we can invite people from AROUND THE WORLD ❤️

**Comment by lpmi-13** [comment]
For now, I would vote to keep some sort of timezone indicator on there, and either localise the time (if jekyll supports that easily) or use something like moment.js to check whether its British Summer Time and show the GMT equivalent of UK 9:30AM

**Comment by lpmi-13** [comment]
I'll raise a separate issue to more broadly address scaling the event to a global participant group, and what that might look like.

**Comment by olorton** [comment]
I'd either display it as:

- 9:30am BST
- 9:30am BST (UTC +1)

Or you could get clever and display it in their time using `Date.getTimeZoneOffset()`

**Comment by djavorszky** [comment]
I vote to keep the timezone there - I'm in UTC+2 myself, so the 9:30 start time for me is 10:30.

It seems like Jekyll has some tools to format the dates, maybe that can be used to display the time and date correctly:

https://learn.cloudcannon.com/jekyll/date-formatting/

**Comment by dev-earthhero** [comment]
I suppose the simplest solution is to just update the hardcoded string, and perhaps add in some other references like:

```
9:30 London | 10:30 Central Europe | 11:30 Whatever is to the right of Central Europe
```

...though it would be super nice if we didn't have to either

1) add in extra entries for additional timezones if/when we get some people from the US joining in, which is not outside the realm of possibility.

2) Do something that requires we manually update it when we switch back off British Summer Time at the end of October.

I mean, I don't think it's too much to ask people to calculate what 8:30 UTC is for them, but it would be a nifty UX enhancement if they didn't have to, just not sure the best way to approach that.

**Comment by benfoxall** [comment]
Okay!  I've changed it so that the start time is printed in the current timezone:

image

(hello from 🇮🇪!)

---

## Jekyll Dates

@djavorszky great shout on outputting that through jekyll - that makes is way easier to update

## Intl.DateTimeFormat

@olorton I'd never come across, `getTimeZoneOffset`! It led me to [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) - which lets us print out the name of the default timezone too!

## Preview URLs

I hooked up netlifly, so we now get [deploy previews](https://deploy-preview-28--wizardly-wiles-9029ce.netlify.app/). (the main site is still served through github though).

**Comment by lpmi-13** [comment]
Was gonna suggest netlify deploy previews...good call!!

**Comment by lpmi-13** [comment]
LGTM, though would be nice to confirm that preview is looking good outside of the UK/Ireland

**Comment by TickleThePanda** [comment]
I like it updating on the client automatically! Though, it might be worth keeping the timezone of the host country to give some context to the start time. It might look odd if a hack is starting somewhere at 3am?

The following is probably overkill but you can specify [a Jekyll timezone as `TZ` in the global configuration](https://jekyllrb.com/docs/configuration/options/), for example `Europe/London` which could (not sure in actual implementation it would be very useful) link the time to appropriate daylight savings - unless it's going to be at 8:30am in October/November?

Not sure if it's referenced anywhere but I came across the following which mentions an outdated date and time while looking at the current global config:
https://github.com/remotehack/remotehack.github.io/blob/ec5f99ce35ac3432f737c1a8f460b76fc502cd18/_config.yml#L24

**Comment by lpmi-13** [comment]
I mean, by "overkill", we mean adding an additional line in the config, which means it never has to be thought about again, which feels much more elegant. So I'm 100% in favour of that.

I had opened up that other issue to start a discussion about how vastly different timezones could also take part, and maybe that's what I'll plan to work on during this month's remote hack.

**Comment by benfoxall** [comment]
I've added the config (and updated some of the other fields a bit).  Doesn't seem to have made a different to the output date, but doesn't hurt!  :+1:

**Comment by djavorszky** [comment]
🕐 It's working beautifully for me 🎉 

image

**Pull request merged**
